### ISSUE TITLE
Login not quite working correctly

### ISSUE THREAD

**Issue by b3none** [csgo-league/csgo-league-web#10]
Briefly described in #8

**Comment by FlowingSPDG** [comment]
still not working :/
![image](https://user-images.githubusercontent.com/30292185/58752565-f3901d80-84eb-11e9-87d3-bb61524d788c.png)

**Comment by b3none** [comment]
Fixed by https://github.com/csgo-league/csgo-league-web/commit/a5c4874dfd3c6b420a1438a9f447eaafef60779b
