### ISSUE TITLE
sorry for my bad english...I can not understand the part about DB Migration

### ISSUE THREAD

**Issue by LemonPAKA** [csgo-league/csgo-league-web#14]
I can not understand the part about DB Migration and one more question, I am using a web panel for host website...can this use with nginx ?

**Comment by b3none** [comment]
Hey, yeah so you want to connect the database and run the migrations to create any tables that are required. So long as you’ve got PHP installed it should work. I haven’t worked with Nginx but I’d assume it will work just fine with nginx.

**Comment by LemonPAKA** [comment]
> Hey, yeah so you want to connect the database and run the migrations to create any tables that are required. So long as you’ve got PHP installed it should work. I haven’t worked with Nginx but I’d assume it will work just fine with nginx.

I edit the env.php   but where is the vendor one? i am not using Xshell or putty

**Comment by b3none** [comment]
You need to run composer install then the migrations command should work as expected

**Comment by LemonPAKA** [comment]
> You need to run composer install then the migrations command should work as expected

looks like I need to write a rewire rule ...what it looks like?

**Comment by asherkin** [comment]
Something like this assuming you're already setup for serving PHP files:
```
server {
    listen       80;
    listen       [::]:80;
    server_name  league.your.domain;
    root         /var/www/csgo-league-web/web;

    # This depends on your distro, without it you'll need a block to pass PHP requests to php-fpm.
    include /etc/nginx/default.d/*.conf;

    location / {
        try_files $uri /index.php$is_args$args;
    }
}
```

**Comment by LemonPAKA** [comment]
> Something like this assuming you're already setup for serving PHP files:
> 
> ```
> server {
>     listen       80;
>     listen       [::]:80;
>     server_name  league.your.domain;
>     root         /var/www/csgo-league-web/web;
> 
>     # This depends on your distro, without it you'll need a block to pass PHP requests to php-fpm.
>     include /etc/nginx/default.d/*.conf;
> 
>     location / {
>         try_files $uri /index.php$is_args$args;
>     }
> }
> ```

https://imgur.com/LCZ2hXe
https://imgur.com/pV0EPcX
https://imgur.com/qKFq2ii
https://imgur.com/xLdxfWy
how to fix this?

**Comment by b3none** [comment]
Looks like you've got this setup now, I'm going to close this issue.
