### ISSUE TITLE
i got not response error

### ISSUE THREAD

**Issue by im6705** [csgo-league/csgo-league-web#21]
**Screenshots**
![image](https://user-images.githubusercontent.com/10539689/59585543-b3e84900-911b-11e9-89b8-d462fcf45309.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.02
err code is ERR_EMPTY_RESPONSE

**Comment by B3none** [comment]
Hey, looks like you’ve not installed it correctly. Perhaps check your apache config / the url you’re trying to visit?

**Comment by im6705** [comment]
![image](https://user-images.githubusercontent.com/10539689/59586424-e4c97d80-911d-11e9-9b39-7ec4d3d55a32.png)
and my server ip is this http://101.101.164.218/

**Comment by B3none** [comment]
The ServerName should usually be a URL. If you’re setting an IP you could try replacing *:80 with ip:80

I haven’t done this myself. I’d assume the problem here is in your apache config.

**Comment by im6705** [comment]
i got another error 404 not found...
ps. im so sorry about many question.

**Comment by B3none** [comment]
I'd say point a domain at your box and do it that way.

**Comment by im6705** [comment]
i guess my server error. cus i buy domain. and add it. but not work :(

**Comment by im6705** [comment]
i try reinstall and follow step by step and got [ERR_TOO_MANY_REDIRECTS] this. its also apache config error?(now new domain is league.d-srv.com)

**Comment by B3none** [comment]
Hey, sorry but this isn't an error with our code. Those installation steps worked for everyone else. If you are able to figure out what's going wrong then please do not hesitate to submit a pull request with the relevant changes in the `README.md`
