### ISSUE TITLE
blank page.

### ISSUE THREAD

**Issue by im6705** [csgo-league/csgo-league-web#23]
Hello Again,
when open up my server domain page [league.(mydomain.com)] i got blank page.
i cant catch any error code(its not in apache2 log file)... anything solution about this ?
and. sorry about my english skill.

**Comment by B3none** [comment]
Try going to `league.your.domain/home`

**Comment by im6705** [comment]
![image](https://user-images.githubusercontent.com/10539689/59808266-8d522a00-9336-11e9-8d76-c5eb10b3df7b.png)

yeap when i connect to `league.mydomain` auto redirect to `;eague.mydomain/home`  and nothing to show. maybe `env.php` path mean not panel path?

**Comment by B3none** [comment]
You need to fix your permissions for the `app/cache/twig` directory.

**Comment by im6705** [comment]
![image](https://user-images.githubusercontent.com/10539689/59888045-bc34d280-9400-11e9-8c84-9d7f550d7423.png)
try fix permissions. and change to 777 but nothing change.

**Comment by B3none** [comment]
can you tell me whether the twig directory is actually populated with data please.

**Comment by im6705** [comment]
![image](https://user-images.githubusercontent.com/10539689/59921357-64ca4d00-9468-11e9-82ca-fbdc11c4f80b.png)
wow there is nothing in there. how can i fix?
