### ISSUE TITLE
Step by Step Guide

### ISSUE THREAD

**Issue by dMwJr** [csgo-league/csgo-league-web#25]
I am not to big on Ubuntu or any Linux distro for that matter and i am not sure i even had mine setup correctly. But i got completely lost or stuck on migrating the DB. I know the steps that you have written out are probably pretty good for non-beginners but is there a chance we could get a little more of a step by step install guide? Maybe some advice on the best way to install the prereqs or a quick run through of what should be installed first etc. Splewis had a pretty good install guide for get5-web that i was successful at and it was detailed but not too detailed. Just a request, thank you. In the meantime il try to figure out what i did wrong.

**Comment by B3none** [comment]
Hey, you'll need to install composer via the `composer install` command. That should create a folder called `vendor/` which will contain a sub directory called `bin/` then step that says run `./vendor/bin/phpmig migrate`. This is something that you'll need to run in the command line when you're at the root of the project. Hope this helps! :) Happy to answer anymore questions you have.

**Comment by dMwJr** [comment]
Thanks for the tip, il take a look at it today. Thought i did the composer install correctly but didnt see the directory. Il post back with results. Thank you for the help.

**Comment by dMwJr** [comment]
ok turns out that my php install was scuffed. Reinstalled php7.2 and modules. ran `composer install` and `./vendor/bin/phpmig migrate` no issues and i was able to get the site up and running on localhost:5000.
