### ISSUE TITLE
ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by CSGO4WEB** [csgo-league/csgo-league-web#26]
Hello! After trying to install I got an error in my browser: ERR_EMPTY_RESPONSE 
When I Access to /home it shows me a white page with no content...
I've made everything correctly but it's not working.
- DataBase Migration - OK
- Composer Install - Ok
- All requirements - OK

Could you please help me trying to find out what's the problem? Saw another posted issues with same error but none of them was solved... 
It would be great if you can help me!

Web URL: http://jogos.csgo4web.com

Waiting for your response.

**Comment by B3none** [comment]
Take a look at: https://github.com/csgo-league/csgo-league-web/issues/25#issuecomment-516705198

**Comment by CSGO4WEB** [comment]
It doesn't make any sense... 
So... How can reinstalling PHP will help? Already ran composer install and ./vendor/bin/phpmig migrate.
Need to understand why this happens...

**Comment by dMwJr** [comment]
im having the same issue as well now

**Comment by B3none** [comment]
Perhaps give this a whirl: https://github.com/csgo-league/csgo-league-web/issues/28#issuecomment-519414491

**Comment by CSGO4WEB** [comment]
Not working for me... Same problem.... :c

**Comment by dMwJr** [comment]
can you screenshot your permissions for `/var/www/` and `/csgo-league-web/`?

**Comment by CSGO4WEB** [comment]
The directory `/var/www is 777` and `var/www/play is 777` (To tall files and directories)

**Comment by dMwJr** [comment]
and they all belong to the same owner and the www-data group?

**Comment by CSGO4WEB** [comment]
Yes, I executed the commands u suggested

**Comment by B3none** [comment]
This looks to have gone stale, if you're still running into issues just re-open the ticket and we can address them again.
