### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by freedigin** [csgo-league/csgo-league-web#27]
redirected you too many times.

ERR_TOO_MANY_REDIRECTS

i already changed **_'WEBSITE' => '/home'_** to _**'WEBSITE' => ''**_ but this error still happens

**Comment by B3none** [comment]
This could be a problem with Apache / how you setup your subdomain

**Comment by freedigin** [comment]
pointing league.mydomain.com to my ip apache server with A RECORD

**_csgo-league-web.conf_**
```
<VirtualHost *:80>
    ServerName league.mydomain.com

    DocumentRoot /var/www/csgo-league-web/web

    <Directory /var/www/csgo-league-web/web>
        Options -Indexes
        FallbackResource /index.php
    </Directory>
</VirtualHost>
```

**_env.php_**
```
    'MATCHES_PAGE_LIMIT' => 10,
    'PLAYERS_PAGE_LIMIT' => 12,
    'WEBSITE' => '/home',
    'URL' => '',
```

**Comment by ilyasafr** [comment]
when i set **env.php** without **/home**

**_env.php_**
```
    'MATCHES_PAGE_LIMIT' => 10,
    'PLAYERS_PAGE_LIMIT' => 12,
    'WEBSITE' => '',
    'URL' => '',
```

my web got blank page

**Comment by freedigin** [comment]
now i got this response, but the page not showing

`{"status":500}`

**Comment by dMwJr** [comment]
i have that issue as well

**Comment by freedigin** [comment]
already fixed it

thanks

**Comment by dMwJr** [comment]
@froidice could you give us some info on how you fixed it?
