### ISSUE TITLE
Installation is broke

### ISSUE THREAD

**Issue by dMwJr** [csgo-league/csgo-league-web#28]
I have set this up at least 15+ times now. All prerequisites met everytime. No issues with the build out and DB migrate. setup env.php and csgo-league-web.conf. And the site doesn't work, its always too many redirects, i remove /home and then just a blank page. There is something that isn't correct with the PHP or somehow installing it and skipping a step in the tutorial. Could you please post a step by step include what destro of Linux, and version of prerequisites ?

**Comment by dMwJr** [comment]
PERMISSIONS PERMISSIONS PERMISSIONS!!!
However you end up installing everything, even if you do it all in root go back and reset correct permissions.

Example: 

```
adduser <username>

sudo adduser <username> www-data
sudo chown -R www-data:www-data /var/www
sudo chmod -R g+rw /var/www

```
in the end im an idiot but i finally figured it out, sorry for laying blame were it wasn't due!

**Comment by B3none** [comment]
If you feel like it I'd appreciate a PR adding those steps to the installation / FAQ of the README. :smile_cat:
