### ISSUE TITLE
Add migration tutorial on README.MD

### ISSUE THREAD

**Issue by FlowingSPDG** [csgo-league/csgo-league-web#3]
Thanks for publishing such a nice softwere!
I've tried this,but I was stucking on migration section :/
so,please add migration section on README.MD for other ppl
``./vendor/bin/phpmig migration``

**Comment by b3none** [comment]
Hey, thanks for using the software, totally overlooked that one :P I'm happy to merge a PR with these changes to the readme implemented 👍

**Comment by FlowingSPDG** [comment]
Hi! thanks for super-fast response :D
I've sent PR for README.md,please check it :)

**Comment by b3none** [comment]
Merged 💯

**Comment by FlowingSPDG** [comment]
ty,keep it up!
