### ISSUE TITLE
{"status":500} error after install

### ISSUE THREAD

**Issue by Shaneajm** [csgo-league/csgo-league-web#34]
Hi! I got this running on a local server so I decided to try it on a VPS.

I followed the install tutorial in the README and I keep getting an `{"status":500}` error when I visit the website. Any idea as to why? Local works fine but I tried installing twice on two different VPS providers and I get this.

**Comment by B3none** [comment]
Hey Shane, sorry to hear you’re running into problems. If I recall correctly there’s an exception helper with a check for local or not. If you comment the if statement it’ll actually pass you the error 🙂 please do be aware that this still isn’t quite as good as I want it and that the discord bot was the final piece which needs making. In the meantime I’m going to add a way to manually start a game via a command.

**Comment by B3none** [comment]
@Shaneajm https://github.com/csgo-league/csgo-league-web/blob/6c417a32129a7071b94aa2c21e354478701de9a2/src/Helpers/ExceptionHelper.php#L24

**Comment by Shaneajm** [comment]
Thanks for the info! I commented the line out and checked my apache log. This is an error I found in it:

 `[php7:error] [pid 6003] [client xx.xxx.xx.xx:34376] script '/var/www/csgo-league-web/web/external.php' not found or unable to stat`

 I'm not sure why it's requesting that file because it doesn't exist in the main repo or in my clone. 

EDIT: After refreshing the page a few times this also showed up in the apache log.
```
[Wed Dec 18 19:56:42.954232 2019] [php7:emerg] [pid 8152] [client IP_OF_CLIENT:58974] PHP Parse error:  syntax error, unexpected 'die' (T_EXIT), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/csgo-league-web/src/Helpers/ExceptionHelper.php on line 32
[Wed Dec 18 19:56:42.954309 2019] [php7:error] [pid 8152] [client IP_OF_CLIENT:58974] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
[Wed Dec 18 19:57:06.081487 2019] [php7:emerg] [pid 8145] [client IP_OF_CLIENT:52152] PHP Parse error:  syntax error, unexpected 'die' (T_EXIT), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/csgo-league-web/src/Helpers/ExceptionHelper.php on line 32, referer: http://IP_OF_SERVER:80/
[Wed Dec 18 19:57:06.081545 2019] [php7:error] [pid 8145] [client IP_OF_CLIENT:52152] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0, referer: http://IP_OF_SERVER/ 
```

( `X` and `IP_OF_CLIENT` are in place of my IPs)

**Comment by B3none** [comment]
Just quickly googling the first error lead me to [this SO post](https://serverfault.com/questions/183725).

As for the errors you're getting; it looks like your edits to the `ExceptionHelper.php` weren't quite right.

I've joined your community discord so I may be able to help more there. We could then either update the installation steps or post the solution to your problem here.

**Comment by whopiyush** [comment]
So what's the fix?

**Comment by B3none** [comment]
@officialpiyush it was a file permissions error.
