### ISSUE TITLE
Add a discord support server

### ISSUE THREAD

**Issue by whopiyush** [csgo-league/csgo-league-web#36]
**Is your feature request related to a problem? Please describe.**
Make a discord support server. It would be easy for people to interact and get support easy and fast.

**Describe the solution you'd like**
I would like to suggest making a discord server for it

**Comment by whopiyush** [comment]
I fixed my issues, but I shall keep this issue open.

**Comment by B3none** [comment]
I'll get one setup now and then put a permanent invite link in the project's README.

**Comment by B3none** [comment]
@officialpiyush https://discord.gg/b5MhANU
