### ISSUE TITLE
Invalid return protocol

### ISSUE THREAD

**Issue by thboss** [csgo-league/csgo-league-web#37]
I got steam error when login:

Sorry!
An error was encountered while processing your request:
Invalid return protocol

OS ubuntu 16.04
php 7.2

**Comment by whopiyush** [comment]
In your env.php, what is your `URL` variable? It needs to be prefixed with `http://` or `https://`.

**Comment by thboss** [comment]
@officialpiyush 
yeah it's, work fine now,
thanks

**Comment by whopiyush** [comment]
yw. I myself had that problem, so I dug up and found that it needs to be prefixed, took me 1 day to figure out. Glad that someone benefited :)
