### ISSUE TITLE
Endpoint for batch-fetching player profiles

### ISSUE THREAD

**Issue by cameronshinn** [csgo-league/csgo-league-web#46]
**Is your feature request related to a problem? Please describe.**
We might want to implement a "server leaderboard" in the bot. Would require us to get all of the member profiles (probably cache them) and save stats.

**Describe the solution you'd like**
An endpoint where one could pass a list of players' IDs and get back all of their profile data. This would eliminate the latency overhead when issuing requests for many players.

**Describe alternatives you've considered**
Could get their profiles individually and it would make the most sense to be doing it all at once, but this would take longer since a request would be needed for each user.

**Comment by B3none** [comment]
This is an excellent idea, I'll get this implemented today!

**Comment by B3none** [comment]
https://github.com/csgo-league/csgo-league-web/commit/d670fcbb158e5b431b8af8bad25ea62752eb57be
