### ISSUE TITLE
Endpoint to set teams by match ID

### ISSUE THREAD

**Issue by cameronshinn** [csgo-league/csgo-league-web#47]
**Is your feature request related to a problem? Please describe.**
For the bot to implement team drafting, the best solution (IMO) would be to set it after the server comes up and have it default to auto-balancing.

**Describe the solution you'd like**
An endpoint to set the teams of the server by match ID (or maybe IP+port?). Should fail if the match has already started or if the match is over (i.e. only works if the match is in the ready-up phase).

**Describe alternatives you've considered**
The alternative would be to require the teams to be set before starting up the server. The team drafting would have to be done preemptively in this case and would require a config setting to choose between auto-balancing or team drafting. This seems more clunky to me because the config would have to be set by and admin and perhaps couldn't be easily changed on the fly (since we don't want admins to have to change this constantly).

**Comment by B3none** [comment]
This'll definitely require more thought. It'll also require some research into the best way to update this information on the game server.

**Comment by cameronshinn** [comment]
Do you think this is worth the time to implement? Could just make it so you have to draft teams before you start the server. However, something similar would need to be implemented if we want to allow map drafting from the bot.

**Comment by B3none** [comment]
I think once we've solved one of those problems we will have both, however, without asking someone who's more in the know about Splewis' get5 I'm really not sure.

We can test some stuff together over the weekend and see if we can get it to work.

It could always be that we implement some sort of server reserving functionality then run through that process knowing that the server won't get taken by another game.

**Comment by cameronshinn** [comment]
Not needed anymore
