### ISSUE TITLE
/players /matches redirects itself forever when system has no users

### ISSUE THREAD

**Issue by FlowingSPDG** [csgo-league/csgo-league-web#8]
**Describe**
/players /matches redirects itself forever when system has no users (or matches).

**Expected behavior**
shows "not found" error

**Screenshots**
![image](https://user-images.githubusercontent.com/30292185/58752157-3ac6e000-84e5-11e9-9cd0-6a3df16322d0.png)

 - OS: WSL Ubuntu
 - Browser Google Chrome
 - Version PHP7.2

**Additional context**
How do I register user btw?

**Comment by b3none** [comment]
You can log in with steam, to actually get players in the system it will need some rankme data. I'll look into fixing this redirect error now.

**Comment by FlowingSPDG** [comment]
I found PHP error when I log in with Steam,probably Content-Type issue?
![image](https://user-images.githubusercontent.com/30292185/58752198-f6880f80-84e5-11e9-80d6-26315e04a7f5.png)
https://github.com/csgo-league/csgo-league-web/blob/77f4d591591325071550b49bc31ec819b507bff0/src/Helpers/SteamHelper.php#L132

**Comment by b3none** [comment]
That's a notice but it should still work, I'll have to look a little further into this and let you know. Just updating the game code atm.

**Comment by FlowingSPDG** [comment]
Alright,thanks! I have to sleep from now.
Again this project is awesome,if you need test ppl/env,please let me know and I'll help it for sure!

**Comment by b3none** [comment]
> Alright,thanks! I have to sleep from now.
> Again this project is awesome,if you need test ppl/env,please let me know and I'll help it for sure!

Would be neat to get this running through some test players, it's still got a few rough edges. The main thing I need to test is the CS:GO statistics because it's a butchered version of Kento's RankMe
